import json
import sys


def generate_contract_graph(input_file, output_file):
    with open(input_file, "r") as f:
        data = json.load(f)

    main_contract = data["main_contract"]
    nodes = [
        {
            "id": main_contract,
            "group": 1,
            "size": data["total_calls"],
            "label": "main contract",
        }
    ]
    links = []

    for contract in data["called_contracts"]:
        nodes.append(
            {
                "id": contract["address"],
                "group": 2,
                "size": contract["count"],
                "label": "called times",
            }
        )
        links.append({"source": main_contract, "target": contract["address"]})

    graph_data = {"nodes": nodes, "links": links}

    with open("contract_graph_template.html", "r") as f:
        html_content = f.read()

    html_content = html_content.replace(
        "// here will be the data generated by python script",
        f"const data = {json.dumps(graph_data, indent=4)};",
    )

    with open(output_file, "w") as f:
        f.write(html_content)

    print(f"Graph has been generated in {output_file}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python generate_bubble.py <input_json_file> <output_html_file>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]
    generate_contract_graph(input_file, output_file)
