on:
  push:
    # branches: [main]
    # paths:
    #   - "webapp/backend/tools/backfill**"
    branches: [chore/cd-for-backfill-pellow]

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Test connection
        run: echo "Runner is working on pellow"

      - name: Pull latest code
        run: |
          git -C /home/raphina/crystal-clear pull

      - name: Restart backfill
        run: sudo systemctl restart crystal-clear-backfill
